### ISSUE TITLE
Sistem güncelliği ?

### ISSUE THREAD

**Issue by serhatgksu** [egcodes/aristotle#2]
Hocam merhaba, öncelikle başarılı bir proje olduğunu söylemek istiyorum. Sorunuma gelirsek eğer, sistem güncel mi onu öğrenmek istiyorum.

Sistem üzerinden tarama yapmak istediğim de her site için benzer bir hata alıyorum. 

Hata çıktısı;

teknoloji webrazzi.com
- Starting [2016-06-23 15:20:35]
      # Source: (1 / 50) http://www.webrazzi.com
  [2016-06-23 15:20:36]
  Main.run: http://www.webrazzi.com:ServerDatabaseHandler instance has no attribute 'cursor'
  Traceback (most recent call last):
  File "mainParseSources.py", line 1164, in run
    newsLinkDict.update(self.getNewsLinkFromSource(present, category, source, newsSourceLink, newsSourceDiffWords, newsSourceBlackWords))
  File "mainParseSources.py", line 365, in getNewsLinkFromSource
    ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;""" % (self.yearMonth))
  File "C:\Users\whoami\Desktop\haber\ServerDatabaseHandler.py", line 25, in executeQuery
    self.cursor.execute(query)
  AttributeError: ServerDatabaseHandler instance has no attribute 'cursor'
  
  ```
  # Time: 0:00:01
  # Insert To Database
  # ---------------------
  ```
- 2016-06-23 15:20:36.941000: Finished [0:00:01.086000] 

---

 # Time: 0:00:00
        # Source: (50 / 50) http://amkspor.sozcu.com.tr
[2016-06-23 15:16:29]
Main.run: http://amkspor.sozcu.com.tr:ServerDatabaseHandler instance has no attribute 'cursor'
Traceback (most recent call last):
  File "mainParseSources.py", line 1164, in run
    newsLinkDict.update(self.getNewsLinkFromSource(present, category, source, newsSourceLink, newsSourceDiffWords, newsSourceBlackWords))
  File "mainParseSources.py", line 365, in getNewsLinkFromSource
    ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;""" % (self.yearMonth))
  File "C:\Users\whoami\Desktop\haber\ServerDatabaseHandler.py", line 25, in executeQuery
    self.cursor.execute(query)
AttributeError: ServerDatabaseHandler instance has no attribute 'cursor'

---

 # Time: 0:00:00
        # Source: (51 / 50) http://www.sporx.com/?giris=ok
[2016-06-23 15:16:30]
Main.run: http://www.sporx.com/?giris=ok:ServerDatabaseHandler instance has no attribute 'cursor'
Traceback (most recent call last):
  File "mainParseSources.py", line 1164, in run
    newsLinkDict.update(self.getNewsLinkFromSource(present, category, source, newsSourceLink, newsSourceDiffWords, newsSourceBlackWords))
  File "mainParseSources.py", line 365, in getNewsLinkFromSource
    ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;""" % (self.yearMonth))
  File "C:\Users\whoami\Desktop\haber\ServerDatabaseHandler.py", line 25, in executeQuery
    self.cursor.execute(query)
AttributeError: ServerDatabaseHandler instance has no attribute 'cursor'

**Comment by egcodes** [comment]
Selamlar, evet proje güncel. Hatanızın sebebi db bağlantı hatası. Şu ikisini yaptınız mı?
1) Db'de bir bir database yaratmak (örneğin haberbus)
2) ServerDatabaseHandler.py file'ında userName, password, ve db ismini yazmak
self.serverHandler = MySQLdb.connect('127.0.0.1', 'root', 'password', 'haberbus');

Bu şekilde indirip sıfırdan denedim problem çıkarmadı. Kolay gelsin.

**Comment by serhatgksu** [comment]
Hocam evet bende sonradan fark ettim hata benden kaynaklıymış. İlginiz için teşekkür ediyorum, iyi çalışmalar dilerim.
